create table if not exists dc_migration_account_response(
data_migration_id Integer not null,
data_migration_owner varchar(255) null,
active_account char null,
data_migration_type_id Integer null,
data_migration_type varchar(255) null,
data_migration_status varchar(255) null,
data_migration_description Integer null,
authorizer_count Integer null,
auth_country varchar(255) null,
auth_region_code Integer null,
exceptions varchar(255) null,
status varchar(255) null,
remarks varchar(255) null,
constraint dc_migration_account_response_pk primary key(data_migration_id));